function fields = provenanceFields(session, kitInfo, quickLookProfile, group, opts)
% provenanceFields  Build ordered producer provenance fields.
%
%   fields = elab.util.provenanceFields(session, kitInfo, quickLookProfile, group).

    arguments
        session (1,1) struct
        kitInfo (1,1) struct
        quickLookProfile (1,1) string
        group (1,1) struct
        opts.loggedAt (1,1) datetime = datetime("now")
        opts.includeSessionContext (1,1) logical = false
        opts.anynmrVersion (1,1) string = ""
        opts.provenanceFile (1,1) string = ""
    end
    fields = [ ...
        elab.util.fieldStruct("data_file_name", session.fileName, "text", group), ...
        elab.util.fieldStruct("data_file_hash", session.hash, "text", group)];
    if opts.includeSessionContext
        dataUnit = "file";
        if isfield(session, "unit")
            dataUnit = string(session.unit);
        end
        fields = [fields, ...
            elab.util.fieldStruct("data_unit", dataUnit, "text", group), ...
            elab.util.fieldStruct("source_path", session.source.source_path, "text", group), ...
            elab.util.fieldStruct("source_host", session.source.source_host, "text", group), ...
            elab.util.fieldStruct("source_mtime", session.source.source_mtime, "datetime-local", group), ...
            elab.util.fieldStruct("logged_at", opts.loggedAt, "datetime-local", group), ...
            elab.util.fieldStruct("schema_version", elab.util.schemaVersion(), "text", group)];
    end
    fields = [fields, ...
        elab.util.fieldStruct("kit_version", kitInfo.version, "text", group), ...
        elab.util.fieldStruct("kit_commit", kitInfo.commit, "text", group), ...
        elab.util.fieldStruct("matlab_version", string(version), "text", group), ...
        elab.util.fieldStruct("parser", session.info.parser, "text", group), ...
        elab.util.fieldStruct("quicklook_profile", quickLookProfile, "text", group)];
    if opts.anynmrVersion ~= "" && opts.provenanceFile ~= ""
        fields = [fields, ...
            elab.util.fieldStruct("anynmr_version", opts.anynmrVersion, "text", group), ...
            elab.util.fieldStruct("provenance_file", opts.provenanceFile, "text", group)];
    end
end
