function document = provenanceDocument(session, kitInfo, quickLookProfile, opts)
% provenanceDocument  Build deterministic NMR preview provenance content.
    arguments
        session (1,1) struct
        kitInfo (1,1) struct
        quickLookProfile (1,1) string
        opts.anynmrInfo (1,1) struct = elab.util.anynmrInfo(verify=true)
    end
    source = opts.anynmrInfo;
    document = struct("provenance_version", "1", "kit", kitInfo, ...
        "matlab_version", string(version), "input", struct( ...
        "data_file_name", session.fileName, "data_unit", session.unit, ...
        "data_file_hash", session.hash, "data_file_manifest_hash", session.manifest.fullHash), ...
        "parser", "elab.io.parseBrukerExperiment", "anynmr", struct( ...
        "url", string(source.url), "tag", string(source.tag), "commit", string(source.commit), ...
        "files_hash", string(source.files_hash), "files_verified", logical(source.files_verified)), ...
        "processing", struct("steps", session.parsed.spectrum.steps, ...
        "preview_profile", quickLookProfile));
end
