function md = buildTestCatalog(projectRoot)
% buildTestCatalog  Build the Markdown test catalog from the test folders.
%
%   md = buildTestCatalog(projectRoot)
%
%   Returns the text of docs/test_catalog.md as a string. The text is
%   derived only from tests/unit and tests/smoke and from the function
%   files under src/, so it is deterministic: no dates, no run results.
%   scripts/build_test_catalog.m writes it to disk, and TestTestCatalog
%   fails when the committed file differs from what this returns.
%
%   The catalog has two parts:
%     1. Each test file with its one-line description and its test points.
%        A parameterized test counts once per parameter set, as in the
%        test runner, so the total equals the runner's Total.
%     2. Each function under src/ with the test files that call it by
%        name. A function called only through another function is listed
%        with no test file; that is indirect coverage, not no coverage.

    arguments
        projectRoot (1,1) string
    end

    testDirs = ["tests/unit", "tests/smoke"];
    lines = [
        "# Test Catalog"
        ""
        "> Generated by `scripts/build_test_catalog.m` from `tests/unit` and"
        "> `tests/smoke`. Do not edit by hand: regenerate after adding, renaming"
        "> or removing a test. `TestTestCatalog` fails while this file is stale."
        ""
        ];

    [fileRows, totalPoints, testTexts] = localTestFiles(projectRoot, testDirs);
    lines = [lines
        "Total test points: " + totalPoints + " (unit + smoke)."
        ""
        "## Test files"
        ""
        "| File | Points | Description |"
        "|---|---|---|"
        fileRows.summary
        ""];

    for k = 1:numel(fileRows.detail)
        lines = [lines; fileRows.detail{k}]; %#ok<AGROW>
    end

    lines = [lines
        "## Functions under src/ and the test files that call them"
        ""
        "Called by name in the test source. Functions reached only through"
        "another function show `-`; they are covered indirectly, if at all."
        ""
        "| Function | Called by |"
        "|---|---|"
        localFunctionRows(projectRoot, testTexts)
        ""];

    md = strjoin(lines, newline);
end

function [rows, totalPoints, texts] = localTestFiles(projectRoot, testDirs)
    rows.summary = strings(0, 1);
    rows.detail = {};
    totalPoints = 0;
    texts = struct("name", {}, "text", {});
    for d = testDirs
        folder = fullfile(projectRoot, d);
        suite = testsuite(char(folder));
        files = dir(fullfile(folder, "*.m"));
        names = sort(string({files.name}));
        for f = names
            [~, base] = fileparts(f);
            relPath = d + "/" + f;
            text = string(fileread(fullfile(folder, f)));
            texts(end + 1) = struct("name", relPath, "text", text); %#ok<AGROW>
            inFile = suite(string({suite.TestParentName}) == base);
            if isempty(inFile)
                continue
            end
            procs = string({inFile.ProcedureName});
            [uniq, ~, idx] = unique(procs);
            counts = accumarray(idx(:), 1);
            totalPoints = totalPoints + numel(inFile);
            rows.summary(end + 1, 1) = "| [`" + relPath + "`](../" + relPath + ") | " + ...
                numel(inFile) + " | " + localDescription(text, base) + " |";
            detail = ["### `" + base + "`"; ""];
            for m = 1:numel(uniq)
                item = "- `" + uniq(m) + "`";
                if counts(m) > 1
                    item = item + " (x" + counts(m) + " parameter sets)";
                end
                detail(end + 1, 1) = item; %#ok<AGROW>
            end
            rows.detail{end + 1} = [detail; ""];
        end
    end
end

function desc = localDescription(text, base)
    % First comment line of the form "% <Name>  <description>".
    tok = regexp(text, "(?m)^\s*%\s*" + base + "\s+(.+?)\s*$", "tokens", "once");
    if isempty(tok)
        desc = "(no description line)";
    else
        desc = strrep(string(tok{1}), "|", "\|");
    end
end

function rows = localFunctionRows(projectRoot, testTexts)
    srcRoot = fullfile(projectRoot, "src");
    files = dir(fullfile(srcRoot, "**", "*.m"));
    names = strings(0, 1);
    for k = 1:numel(files)
        rel = erase(string(fullfile(files(k).folder, files(k).name)), string(srcRoot) + filesep);
        parts = split(replace(rel, "\", "/"), "/");
        [~, base] = fileparts(parts(end));
        pkgs = parts(startsWith(parts, "+"));
        if isempty(pkgs)
            names(end + 1, 1) = base; %#ok<AGROW>
        else
            names(end + 1, 1) = strjoin([extractAfter(pkgs, 1); base], "."); %#ok<AGROW>
        end
    end
    names = sort(names);

    rows = strings(numel(names), 1);
    for k = 1:numel(names)
        callers = strings(0, 1);
        pattern = "(?<![\w.])" + regexptranslate("escape", names(k)) + "(?![\w])";
        for t = 1:numel(testTexts)
            if ~isempty(regexp(testTexts(t).text, pattern, "once"))
                callers(end + 1, 1) = "`" + testTexts(t).name + "`"; %#ok<AGROW>
            end
        end
        if isempty(callers)
            callerCell = "-";
        else
            callerCell = strjoin(callers, ", ");
        end
        rows(k) = "| `" + names(k) + "` | " + callerCell + " |";
    end
end
